name = "mysticdesign"
main = "functions/api/index.js"
compatibility_date = "2024-04-01"
compatibility_flags = ["nodejs_compat"]

# Bind your R2 bucket
[[r2_buckets]]
binding = "UPLOADS"
bucket_name = "mysticbucket"

[[d1_databases]]
binding = "DB"
database_name = "mysticdatabase"
database_id = "2cabb59a-e29d-43b0-a998-b1686d88eba0"

# Environment variables
[vars]
PUBLIC_URL = "https://3e2b146abd5ec58f4de9391615044873.r2.cloudflarestorage.com/mysticbucket"
